version: "3.7"

# 컴퓨터들
services:

    # 컴퓨터 이름
    my-backend:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./index.js:/myfolder/index.js
            - ./email.js:/myfolder/email.js
        environment:
            # Dockerfile volumes 실시간 반영 안되는 문제 관련)
            #
            # 윈도우 환경 도커 쓸 때 문제가 되는 부분 해결 코드 
            # chokidar 모듈 : WebPack과 Babel이 파일들의 모니터링하기 위해 사용하는 모듈
            - CHOKIDAR_USEPOLLING=true 
        ports:
            - 3000:3000

    # 컴퓨터 이름
    my-database:
        image: mongo:5
        ports:
            - 27017:27017
